### ISSUE TITLE
Clarification on Nodeeditor support for child windows

### ISSUE THREAD

**Issue by AK-test-PK** [thedmd/imgui-node-editor#102]
referring to the issue#67.
"Widgets which create child windows don't cope well with canvas node editor use."

What could be the reason behind this ?

**Comment by thedmd** [comment]
Child Windows are actual ImGui windows without frame, they have their own ImDrawList, cliprects and rest of the state. This is like having ImGui::Dummy() in main window, and child window drawn on top. Canvas has no knowledge of child window, since it is looking at only ImDrawList output (aka. generated widget geometry) and transform it.

With hooks recently added to ImGui it may be possible to inject Canvas into the window indirectly. That would touch a lot more ImGui internal state, this is moving target and I feel this is out of scope of what Canvas should do. It meant to be simple view over infinite canvas.

In my code I avoid controls with child window often by making a popup with editor I want. Popup logic is executed when canvas is suspended (aka ImGui see normal MousePos). It works for node editor so far.

Does that answer your question?

**Comment by AK-test-PK** [comment]
Yes. Thank you for the explanation.
