### ISSUE TITLE
How to set the width of a node?

### ISSUE THREAD

**Issue by OriolCS2** [thedmd/imgui-node-editor#136]
How can I set the width of a node?

Thanks!!

**Comment by thedmd** [comment]
After calling `BeginNode` you can call `ImGui::Dummy(ImVec2(300.0f, 0.0f))`, to make sure node content width is `300`.

Your probably want also to save cursor position and restore it after calling `Dummy`, so you can push content from the top left. Otherwise some spacing will be added after `Dummy` widget.
