### ISSUE TITLE
Save/Load nodes and links to json 

### ISSUE THREAD

**Issue by aabilityuk** [thedmd/imgui-node-editor#141]
Hi, dear community! Could anybody please help me to find out how to make a save/load logic for all nodes and links to/from json., It would be great to see a code sample and any advices would be appreciated!!! Thank you very much

**Comment by thedmd** [comment]
Hi, did you looked at blueprint example?

Callback are called after node state change and you can save it. To restore previous state you can call `ed::RestoreNodeState()`.

https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/blueprints-example/blueprints-example.cpp#L498-L520

Save/Restore state is clunky, but is getting job done. Next version may improve on the API.

**Comment by SadE54** [comment]
Personally , I used a third party json serializer (nlohmann json). It allows me to save/process arbitrary data , including new fields for my specific application , and without touching to the node library .

**Comment by aabilityuk** [comment]
> Hi, did you looked at blueprint example?

Hi, yes i did

> Callback are called after node state change and you can save it. To restore previous state you can call `ed::RestoreNodeState()`.

Thank you for explanation, i try to save and restore the within the blueprints example buttons:

![изображение](https://user-images.githubusercontent.com/78211227/147246233-37f8dffd-bcd7-4105-8363-f1e3ebc15bea.png)

it save and store only the location of the node. 

But I need saving the whole state of all nodes,links,pins to json, then i close the program and after i start the program i what to restore all this nodes, links, pins and so on to it's state before i close the program!!!

Could you please explain me how to achieve this approach? or maybe  there is a code example? Thank you

**Comment by aabilityuk** [comment]
> Personally , I used a third party json serializer (nlohmann json). It allows me to save/process arbitrary data , including new fields for my specific application , and without touching to the node library .

Hi, thank you for reply! is it possible to achieve the goal i posted above with nlohmann?  If so could you share the example please ? Actually i strongly want to be able to make the save/restore option using the original NodeEditor without third parties libs...

**Comment by aabilityuk** [comment]
Dear, @thedmd 

please help me to make File-> save/ File-> Load. I want to be able to save/load the whole node-editor state (with all nodes, links,pins). It is very important to my project and i couldn't release it without this feature. Thank you very much!!!!

**Comment by thedmd** [comment]
Node Editor does not hold more that than returned by callbacks.

Saving and loading state of your data is not in the scope of this project, rather something you need to have on your side. Blueprint example show how one can build an editor and provide mock data that is generated on the fly.

On `feature/blueprint-next` I started to build another example which is build on top of real functional blueprints. Bear in mind is is still work in progress and is on the stage when I do experiment with saving/loading. I didn't touch it for some time, so it may not even work out of the box.

---

To save/load data internally, I'm using `crude_json.h` in which I mimic nlohmann API. Library is simple and bare bones. No descriptive errors while parsing json, no exceptions, no full nlohmann API parity (only some API functions are implemented). Library does job done, even passed many test with an exception of one related to encoding. It works under assumption input and output is utf-8.

Save data format is considered implementation detail and may change one day. Data was never guaranteed to be in json format. At this point however it is very unlikely this will ever change due to backward compatibility.

**Comment by aabilityuk** [comment]
@thedmd 
Thank you for feed back!!! I will take a deep look on the next branch you provided and try to find a beta you made about loading/saving logic!!! What a pity there is no aout of the box desigion(( 

And hope to see the official implementation of save/load feature

**Comment by aabilityuk** [comment]
@thedmd 

Wow, it's completly different technic in compare with the first blueprints example. 
Dear developer of this great library let me ask a couple questions about the new blueprints2-example:

1. How to make not a BluePrint, but Simple node?
2. How to add picture to the node background or to the node Middle? In the previous version i used a ImGui::Image() for this task.
3. How to enumerate and get pins, links, nodes? In the previous version i used for(auto& node : s_Nodes) and for(auto& link : s_Links) for this.

Thank you one more time for an excellent tool you made for public!!!!

**Comment by thedmd** [comment]
Original blueprint example hold answers to both of your question. Code drawing custom looking nodes is there.
