### ISSUE TITLE
Dependency missing.

### ISSUE THREAD

**Issue by Stanlyhalo** [thedmd/imgui-node-editor#149]
I'm using imgui 1.83 docking, and I recently started getting into this extension, but it seem that the dependency (optional of course): https://github.com/thedmd/imgui/tree/feature/draw-list-fringe-scale is no longer available. Did the name change?

Edit*: Also, if any dependency is still working or does work as of now, how do I properly download it, does it require overwriting my current imgui files?

**Comment by thedmd** [comment]
It was merged to ImGui 1.80 (17909):
```
94a4322: ImDrawList: Internals: Add ability to scale anti-alias fringe. This enable users to keep geometry sharp while scaling vertex buffer content.
```

I need to update readme to reflect that.

**Comment by Stanlyhalo** [comment]
So because I'm using 1.83, it should be there, but how do I enable it?

**Comment by thedmd** [comment]
It should work out of the box.
Node Editor use template magic to detect if `ImDrawList::_FringeScale` exists.
Does it not work for you?

**Comment by Stanlyhalo** [comment]
It doesn't seem to work, things still stay at the same resolution and text becomes more blurry when zooming in.

**Comment by thedmd** [comment]
`_FringeScale` does help with making shapes node is drawn with sharp when zoomed in or out.
It does not help with keeping font sharp. What I did in my editor is to setup two fonts: x1 for normal when zoomed out, x4 used when zoomed in.

On [HiDPI branch](https://github.com/ocornut/imgui/issues/1786#issuecomment-1002349827) you can find patches for ImGui that allow you to generate fonts with greater density but roughly¹ same metrics, so they will stay sharp when zoomed in, but does not alter widgets size.

---

1) Roughly, because FreeType may use hinting to better align glyphs to the grid, if you disable hinting metric should be identical.

**Comment by Stanlyhalo** [comment]
I'll close this, since it seems in my place, the best way to solve this, is to just switch out the font with an identical higher resolution font.
