### ISSUE TITLE
What's the point of PinKind?

### ISSUE THREAD

**Issue by codecnotsupported** [thedmd/imgui-node-editor#198]
https://github.com/thedmd/imgui-node-editor/blob/2f99b2d613a400f6579762bd7e7c343a0d844158/examples/basic-interaction-example/basic-interaction-example.cpp#LL127-L138

States that:
```
                // QueryNewLink returns true if editor want to create new link between pins.
                //
                // Link can be created only for two valid pins, it is up to you to
                // validate if connection make sense. Editor is happy to make any.
                //
                // Link always goes from input to output. User may choose to drag
                // link from output pin or input pin. This determine which pin ids
                // are valid and which are not:
                //   * input valid, output invalid - user started to drag new ling from input pin
                //   * input invalid, output valid - user started to drag new ling from output pin
                //   * input valid, output valid   - user dragged link over other pin, can be validated
```
This is a tad bit confusing to me personally.
`Link can be created only for two valid pins`
`it is up to you to validate if connection make sense.`

So in other words links can only be created if they are vaild. But you need to vaildate links yourself.

So you can create links between two input/output `PinKind`s 
![image](https://user-images.githubusercontent.com/2294209/216038677-ed7b5bc4-4200-414e-ab2e-aa6d82479c79.png)
The only difference would seem to be direction of the bézier curve.

Wouldn't it make sense for `PinKind` to be `LinkDirection::Left` & `LinkDirection::Right`

Note: I'm using `imgui-node-editor` through the python interface of `imgui_bundle`

**Comment by Namek** [comment]
pins could be placed in your nodes like from the top, bottom, corners, whatever you like, so you can define them however you like. If in your app everything can be linked to everything from all the sides (all the pins) then you don't need the pin kinds (OR there exists only one kind).

In my case I use just two pin kinds: input, output. That is useful because the linking mechanism works for all the pins but in a moment of making a connection I can validate whether user doesn't try to connect output pin to output pin or input pin to input pin. It's only valid to connect input with output.

**Comment by codecnotsupported** [comment]
Thanks for the info, I'm closing the issue.
