### ISSUE TITLE
Try to build example and run blueprint-example solution

### ISSUE THREAD

**Issue by cherishou** [thedmd/imgui-node-editor#286]
<img width="1790" alt="图片" src="https://github.com/thedmd/imgui-node-editor/assets/17988161/42038d7b-e139-4746-a9ef-bdab6b4e7444">

Hello, i am try to understand how the code work, so try to run a example code.
There is no issue during run cmake -S examples -B build -G "Visual Studio 15 2017 Win64"
but it failed in build, the screen shot show's the code has some syntax issue,which i have no idea how to fix that event i change different version or branch and the issue is the same.

**Comment by misterk99** [comment]
Seems like you frogot to import/link it?

**Comment by AudunVN** [comment]
Having the same issue with a similar version of Visual Studio's build tools, albeit not in an example project - the issue does not appear to be inside user/application code, at least according to the compiler error messages. Struggling a bit to see what is triggering [error C2061](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2061?view=msvc-141), since both me and VSCode can find the declaration of `FlowDirection` just fine from `imgui_node_editor.cpp`.

Think everything after the first error C2061 in imgui_node_editor.cpp can be ignored, as they follow from that error; it's not very surprising that it's unable to find the right member function to overload, the function signature very much doesn't match any more after the compiler dropped the expected second parameter `FlowDirection direction`.

```
"D:\git-repos\mm2hook\MM2Hook.sln" (default target) (1) ->
"D:\git-repos\mm2hook\MM2Hook.vcxproj" (default target) (2) ->
(ClCompile target) ->
  d:\git-repos\mm2hook\src\imgui\node\imgui_node_editor.cpp(2284): error C2061: syntax error: identifier 'FlowDirection' [D:\git-repos\mm2hook\MM2Hook.vcxproj]
  d:\git-repos\mm2hook\src\imgui\node\imgui_node_editor.cpp(2285): error C2511: 'void ax::NodeEditor::Detail::EditorContext::Flow(ax::NodeEditor::Detail::Link *)': overloaded member function not found in 'ax::NodeEditor::Detail::EditorContext' [D:\git-repos\mm2hook\MM2Hook.vcxproj]
  d:\git-repos\mm2hook\src\imgui\node\imgui_node_editor.cpp(2286): error C2065: 'direction': undeclared identifier [D:\git-repos\mm2hook\MM2Hook.vcxproj]
  d:\git-repos\mm2hook\src\imgui\node\imgui_node_editor.cpp(3225): error C2061: syntax error: identifier 'FlowDirection' [D:\git-repos\mm2hook\MM2Hook.vcxproj]
  d:\git-repos\mm2hook\src\imgui\node\imgui_node_editor.cpp(3226): error C2511: 'void ax::NodeEditor::Detail::FlowAnimationController::Flow(ax::NodeEditor::Detail::Link *)': overloaded member function not found in 'ax::NodeEditor::Detail::FlowAnimationController' [D:\git-repos\mm2hook\MM2Hook.vcxproj]
  d:\git-repos\mm2hook\src\imgui\node\imgui_node_editor.cpp(3232): error C2352: 'ax::NodeEditor::Detail::FlowAnimationController::GetOrCreate': illegal call of non-static member function [D:\git-repos\mm2hook\MM2Hook.vcxproj]
  d:\git-repos\mm2hook\src\imgui\node\imgui_node_editor.cpp(3235): error C2065: 'direction': undeclared identifier [D:\git-repos\mm2hook\MM2Hook.vcxproj]
  d:\git-repos\mm2hook\src\imgui\node\imgui_node_editor.cpp(3238): error C3536: 'animation': cannot be used before it is initialized [D:\git-repos\mm2hook\MM2Hook.vcxproj]
```

Seems like there's something it's unhappy with in `imgui_node_editor.h` and/or `imgui_node_editor_internal.h`. Initially thought it was due to trying to build it with v140 (and by extension C++14), but not seeing a change with v141 and C++17.

To be slightly more specific the exact compiler and compiler options used by MSBuild in my case were

```C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\CL.exe /c /Z7 /nologo /W3 /WX- /diagnostics:classic /MP /O1 /Ob1 /Oi /Os /Oy- /GT /GL /D WIN32 /D WIN32_LEAN_AND_MEAN /D _WINDOWS /D NDEBUG /D _USRDLL /D _LUA_EMBED /D IMGUI_IMPL_WIN32_DISABLE_GAMEPAD /D _WINDLL /GF /Gm- /EHa /MD /GS- /Gy- /arch:IA32 /fp:fast /fp:except- /Zc:wchar_t /Zc:forScope /Zc:inline /GR /FAs /Fa"bin\Release\asm\\" /Fo"bin\Release\\obj\/src\imgui\node\/" /Fd"bin\Release\\obj\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:queue /bigobj /std:c++17 src\imgui\node\imgui_node_editor.cpp```

I might be missing something very obvious here... Not too steady in modern C++, and even less so with having to use MSVC to compile it. Will try to see if I can reproduce this with one of the examples from this repository to rule out the issue being due to something in the specific build options for the `mm2hook` project.

---

EDIT: Seems to build perfectly fine with `MSVC\14.39.33519\bin\HostX86\x86\CL.exe` (released this year sometime) and the `/std:c++17` option, albeit with a *lot* of C++17 deprecation warnings. I suspect the issue might be related to MSVC 14.16 and platform toolset v141 supporting a slightly weird mix of features from C++14 and C++17, since it's from right around MSVC's transition from Visual C++ (tm) to supporting more modern standard C++:

- https://learn.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance
- https://learn.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements-2017

Haven't tried `/std:c++14` again yet, but wouldn't be too surprised if that's fine in MSVC 14.39.33519 as well (especially since that's what imgui-node-editor specifies as a dependency in the readme).

Summary so far seems to be that building with MSVC 14.16 seems to have some issues, and running CL with the options `/std:c++14` or `/std:c++17` doesn't appear to change much.

---

EDIT: Yup, MSVC 14.39.33519 with compiler option `/std:c++14` works just fine as expected. Not sure if the recommendation to use `Visual Studio 15 2017 Win64` in the [readme](https://github.com/thedmd/imgui-node-editor/blob/e78e447900909a051817a760efe13fe83e6e1afc/docs/README.md?plain=1#L70) is accurate or up to date, still not ruling out there being something weird with my specific setup. MSVC seems a bit more... *interesting* than the C++ compilers I'm used to.

**Comment by thedmd** [comment]
Thanks for investigation. I'm going to update readme to VS 2022.
