### ISSUE TITLE
Nodes become inactive after scrolling (latest imgui docking branch)

### ISSUE THREAD

**Issue by mtiapko** [thedmd/imgui-node-editor#36]
Steps to reproduce:

1. Clone `imgui-node-editor`
2. Replace all `*.h` and `*.cpp` imgui files in `ThirdParty/imgui` directory by files from latest `imgui docking` branch
3. Add all required `ImGuiKey_*` to enum in `imgui.h`
4. Compile `Examples/BasicInteraction` (for example)
5. Move one of the nodes far away from starting position
6. If try to move it again - **fail**, it is now inactive

This is because the node now is out of the mouse viewport rect. If comment this line
[imgui/imgui.cpp#L4675](https://github.com/ocornut/imgui/blob/5d87ee8d82cbf0c24ab766edca3f424288a2857a/imgui.cpp#L4675) everything works fine, but I think it's a bad idea...

If add this code before line #4675, we will be able to see that mouse viewport rect, out of which nodes become inactive

```C++
auto rect = g.MouseViewport->GetRect();
ImGui::GetWindowDrawList()->AddRect(rect.Min, rect.Max, IM_COL32(255, 0, 0, 255));
```

![mouse-viewport-rect](https://user-images.githubusercontent.com/20288751/63164909-8e4fc100-c032-11e9-857c-efc57a75ac26.png)

**Comment by mtiapko** [comment]
If node rect does not overlaps with canvas rect - it is inactive

**Comment by svnscha** [comment]
I have the same issue.
Due to the clipping mouse viewport `auto emitInteractiveArea = [](ObjectId id, const ImRect& rect)` returns false when outside the mouse viewport, that causes not hovering and no selection.

**Comment by thedmd** [comment]
I will look into that.

**Comment by Learko** [comment]
Same issue, unless I move editor window in the top-left corner of the screen, hovering element outside of viewport doesn't work. Additionally, when viewport is completely out of screen, instead of selecting objects with right click you're just moving whole window.

I believe `ImGuiEx::Canvas::EnterLocalSpace` might be responsible for this problem, you're overwriting `io.MousePos` without modifying viewports pos/size. Transforming viewports like this in `EnterLocalSpace` and then restoring them in `LeaveLocalSpace` kind of solves the problem:
```
ImGuiContext* context = ImGui::GetCurrentContext();
for (ImGuiViewport* viewport : context->Viewports) {
	ImVec2 rMin = viewport->Pos;
	ImVec2 rMax = viewport->Pos + viewport->Size;

	rMin.x = (rMin.x - m_ViewTransformPosition.x) * m_View.InvScale;
	rMin.y = (rMin.y - m_ViewTransformPosition.y) * m_View.InvScale;
	rMax.x = (rMax.x - m_ViewTransformPosition.x) * m_View.InvScale;
	rMax.y = (rMax.y - m_ViewTransformPosition.y) * m_View.InvScale;

	viewport->Pos = rMin;
	viewport->Size = rMax - rMin;
}
```

But that also causes visual artefacts in application window:
![poc](https://user-images.githubusercontent.com/8157199/73365046-71036c00-42cd-11ea-9a00-2616ced88295.gif)

**Comment by Seth-Norton** [comment]
Thank you @Learko, I was running into the same issue. I expect the flickering you're seeing is due to changing _all_ viewports to the canvas-local coordinates. You can try using `ImGui::GetWindowViewport()` to affect only the currently-active viewport.

Under `ImGuiEx::Canvas::EnterLocalSpace`:

```
auto pViewport = ImGui::GetWindowViewport();

m_ViewportPosBackup  = pViewport->Pos;
m_ViewportSizeBackup = pViewport->Size;

ImVec2 rMin = pViewport->Pos;
ImVec2 rMax = pViewport->Pos + pViewport->Size;

rMin.x = (rMin.x - m_ViewTransformPosition.x) * m_View.InvScale;
rMin.y = (rMin.y - m_ViewTransformPosition.y) * m_View.InvScale;
rMax.x = (rMax.x - m_ViewTransformPosition.x) * m_View.InvScale;
rMax.y = (rMax.y - m_ViewTransformPosition.y) * m_View.InvScale;
    
pViewport->Pos  = rMin;
pViewport->Size = rMax - rMin;
```
And in `ImGuiEx::Canvas::LeaveLocalSpace`:
```
auto pViewport = ImGui::GetWindowViewport();

pViewport->Pos  = m_ViewportPosBackup;
pViewport->Size = m_ViewportSizeBackup;
```
(Note: Of course this should only be used with the docking branch of ImGui)

**Comment by Learko** [comment]
@Seth-Norton, you're absolutely right, everything works fine now, thanks.

**Comment by thedmd** [comment]
Thank you for digging into the issue and finding solution.

**Comment by thedmd** [comment]
Yours fix was pushed to master. Thank you!
