### ISSUE TITLE
"Non-standard" use of TextureID passing of custom textures in examples

### ISSUE THREAD

**Issue by crolando** [thedmd/imgui-node-editor#62]
This first post is meant to be mostly a question since I am not super comfortable working with these C++ mechanisms.  

I am looking at your patterns for saving and recovering TextureIDs between `Application_CreateTexture()`, and the other `Application_*Texture()` functions in this file:

https://github.com/thedmd/imgui-node-editor/blob/master/Examples/Common/Application/Source/GLFW/Entry.cpp

For visibility, **saving** the ID looks like this (edited for a clear but contrived example... This should be equivalent to the last line in `Application_CreateTexture()`):
`Guint TextureId = 1;`
`void* void_texture = reinterpret_cast<void*>(TextureId);`

and **retrieving** the ID looks like this (taken from the first line in `Application_FindTexture()`):
`GLuint textureID = static_cast<GLuint>(reinterpret_cast<std::intptr_t>(void_texture));`

I did an investigation of this pattern last night and I think this might be using non-standard C++ rules.  This is the clearest explanation I have seen:
https://stackoverflow.com/questions/48044512/round-trip-safety-of-storing-integer-in-void-pointer

The **most important bit** is this:

> As cppreference points out, there may be several integers that convert to the same pointer.

So in some compiler implementations, this could mean that a GLuint of 1 and 2 both map to a void* of 0x000021, so they both come out as 1, meaning information is lost.

Onto my question... you have a lot more experience with this stuff than I do, so I was wondering:
"Is this a big deal, and would you like me to try to fix it and submit a pull request"?

Thanks for reading!

**Comment by thedmd** [comment]
Hello @crolando,

You're correct. To play safe(r) I should cast `GLuint` to `intptr_t`, then to `void*` (or `ImTextureID`). I choose this pattern because it was used already in backend implementation (see [imgui_impl_opengl2.cpp](https://github.com/ocornut/imgui/blob/751d153ca9f338ec7159e7a250abe198b6a17d73/examples/imgui_impl_opengl2.cpp#L221)).

Although result of such casting is not guaranteed by the C++ standard, this is something that was done for a long time and is very unlikely to break. In new code I stick to pointer-pointer conversion, to avoid such problems in the future. This one can be leaved as is until someone find a machine on which such problem exists.
